# Intro to NumPy

---

In [1]:
import numpy as np

## NumPy Ecosystem
- statsmodel
- scikit-learn
- pandas
- scikit-image
- matplitlib

In [4]:
#create array
array_one = np.array([0,1,3,5,7,9])

#call array
array_one

array([0, 1, 3, 5, 7, 9])

In [6]:
num = [11,22,33,44,55,66,77]

#create second array
array_two = np.array(num)

#call second array
array_two

array([11, 22, 33, 44, 55, 66, 77])

## np.zeros, np.ones, np.empty

In [7]:
#create an array of all zeros using tuple 2,3 (2 rows, 3 columns)
array_zeros = np.zeros((2,3))

#call zero array
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#create an array of all ones using tuple 3,2 (3 rows, 2 columns)
array_ones = np.ones((3,2))

#call zero array
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### array datatypes
- float datatype is create
- to create integer datatype, must specify datatype in input

In [9]:
#create an array with int dtype
array_int_ones = np.ones((3,2), dtype= np.int32)

#call zero array
array_int_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [10]:
#create array of evens (lower bound, upper bound, interval)
array_evens = np.arange(2,24,2)
array_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [11]:
#create array of floats
array_floats = np.arange(1,3,0.3)
array_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])